-- Таблица оружия
CREATE SEQUENCE L2_WEAPON_SEQ;
CREATE TABLE L2_WEAPON (
    L2_ID BIGINT NOT NULL,
    L2_NAME CHARACTER VARYING (255) NOT NULL,
    L2_TYPE CHARACTER VARYING (50) NOT NULL,
    L2_GRADE CHARACTER VARYING (2) NOT NULL,
    L2_P_ATK NUMERIC(3) NOT NULL,
    L2_M_ATK NUMERIC(3) NOT NULL,
    CONSTRAINT PK_WEAPON PRIMARY KEY(L2_ID)
);
ALTER TABLE L2_WEAPON ADD CONSTRAINT UK_WEAPON UNIQUE(L2_NAME);

-- Таблица рецептов
CREATE SEQUENCE L2_RECIPE_SEQ;
CREATE TABLE L2_RECIPE (
    L2_ID BIGINT NOT NULL,
    L2_NAME CHARACTER VARYING (255) NOT NULL,
    L2_TYPE CHARACTER VARYING (50) NOT NULL,
    L2_GRADE CHARACTER VARYING (2) NOT NULL,
    L2_PERCENT NUMERIC(3) NOT NULL,
    L2_LEVEL NUMERIC(2) NOT NULL,
    CONSTRAINT PK_RECIPE PRIMARY KEY(L2_ID)
);
ALTER TABLE L2_RECIPE ADD CONSTRAINT UK_RECIPE UNIQUE(L2_NAME);

-- Таблица связи рецепта и оружия
CREATE SEQUENCE L2_WEAPON_RECIPE_SEQ;
CREATE TABLE L2_WEAPON_RECIPE (
    L2_ID BIGINT NOT NULL,
    L2_WEAPON_ID BIGINT NOT NULL,
    L2_RECIPE_ID BIGINT NOT NULL,
    CONSTRAINT FK_WEAPON_REC_WEAPON FOREIGN KEY(L2_WEAPON_ID) REFERENCES L2_WEAPON(L2_ID),
    CONSTRAINT FK_WEAPON_REC_RECIPE FOREIGN KEY(L2_RECIPE_ID) REFERENCES L2_RECIPE(L2_ID)
);
ALTER TABLE L2_WEAPON_RECIPE ADD CONSTRAINT UK_WEAPON_RECIPE UNIQUE(L2_WEAPON_ID, L2_RECIPE_ID);

-- Таблица расы персонажа
CREATE SEQUENCE L2_RACE_SEQ;
CREATE TABLE L2_RACE (
                           L2_ID BIGINT NOT NULL,
                           L2_NAME CHARACTER VARYING (255) NOT NULL,
                           CONSTRAINT PK_RACE PRIMARY KEY(L2_ID)
);
ALTER TABLE L2_RACE ADD CONSTRAINT UK_RACE UNIQUE(L2_NAME);