-- Таблица оружия
CREATE SEQUENCE L2_WEAPON_SEQ;
CREATE TABLE L2_WEAPON (
    L2_ID BIGINT NOT NULL,
    L2_NAME CHARACTER VARYING (255) NOT NULL,
    L2_TYPE CHARACTER VARYING (50) NOT NULL,
    L2_GRADE CHARACTER VARYING (2) NOT NULL,
    L2_P_ATK NUMERIC(3) NOT NULL,
    L2_M_ATK NUMERIC(3) NOT NULL
);
ALTER TABLE L2_WEAPON ADD CONSTRAINT UK_WEAPON UNIQUE(L2_NAME);
